// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateTodoRes interface {
	createTodoRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteTodoRes interface {
	deleteTodoRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListTodoRes interface {
	listTodoRes()
}

type ListUserRes interface {
	listUserRes()
}

type ListUserTodosRes interface {
	listUserTodosRes()
}

type ReadTodoOwnerRes interface {
	readTodoOwnerRes()
}

type ReadTodoRes interface {
	readTodoRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateTodoRes interface {
	updateTodoRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
